# Generated by Django 5.2 on 2025-04-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0002_alter_order_quantity_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
